//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductoHistorial
    {
        public string NombreProducto { get; set; }
        public string Tipo { get; set; }
        public string NombreProveedor { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
    }
}
